import './globals.css';

import Home from '@/components/Home';

export const metadata = {
  title: 'React Routes',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Home>
          {children}
        </Home>
      </body>
    </html>
  );
}
